name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          - npm run build:lib
          - cp README.md dist/ngx-typed-router
          - cp LICENSE.md dist/ngx-typed-router
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
